[package]
name = "bandwidth"
version = "0.1.0"
authors = ["dhruvdh <dhruv.dhamani@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
packed_simd = "0.3.3"
rayon = "1.2.0"